import { NextRequest, NextResponse } from "next/server";
import { toLocalMeters } from "@/lib/engine/roof";
import { centroid, fitZoom, pixelInImage } from "@/lib/mercator";
import { readBinary, readText } from "@/lib/storage";
import { renderProposalPdf, type OverlayGeom, type PdfImages } from "@/lib/proposal-pdf";
import type { LatLng, ProposalResult } from "@/lib/engine/types";
import type { Narrative } from "@/lib/narrative";

// PDF layout + upload can take a moment — allow the Hobby-tier max.
export const maxDuration = 60;

const W = 515, H = 340;
const EARTH_R = 6_371_000;

function metersToLatLng(origin: LatLng, x: number, y: number): LatLng {
  const cosLat = Math.cos((origin.lat * Math.PI) / 180);
  return {
    lat: origin.lat + ((y / EARTH_R) * 180) / Math.PI,
    lng: origin.lng + ((x / (EARTH_R * cosLat)) * 180) / Math.PI,
  };
}

/** Overlay geometry in W×H pixel space + the map center/zoom to fetch. */
function computeOverlay(result: ProposalResult): { overlay: OverlayGeom; center: LatLng; zoom: number } {
  const poly = result.site.roofPolygon;
  const c = centroid(poly);
  const zoom = fitZoom(poly, W, H);
  const { origin } = toLocalMeters(poly);
  const outline = poly.map((p) => pixelInImage(p, c, zoom, W, H));
  const panels = result.packing.panels.map((p) => {
    const rot = (p.rotDeg * Math.PI) / 180;
    const cos = Math.cos(rot), sin = Math.sin(rot);
    return [
      [-p.w / 2, -p.h / 2], [p.w / 2, -p.h / 2], [p.w / 2, p.h / 2], [-p.w / 2, p.h / 2],
    ].map(([dx, dy]) => {
      const ll = metersToLatLng(origin, p.x + dx * cos - dy * sin, p.y + dx * sin + dy * cos);
      return pixelInImage(ll, c, zoom, W, H);
    });
  });
  const blocked = (result.site.obstructions ?? []).map((o) => o.map((p) => pixelInImage(p, c, zoom, W, H)));
  return { overlay: { w: W, h: H, outline, panels, blocked }, center: c, zoom };
}

async function toDataUri(buf: Buffer | null, mime: string): Promise<string | undefined> {
  return buf ? `data:${mime};base64,${buf.toString("base64")}` : undefined;
}

async function buildPdf(id: string): Promise<{ pdf: Buffer; result: ProposalResult } | null> {
  const text = await readText(`proposals/${id}.json`);
  if (!text) return null;
  const { result, narrative, createdAt, photoCount, hasRender } = JSON.parse(text) as {
    result: ProposalResult; narrative?: Narrative | null; createdAt: string; photoCount?: number; hasRender?: boolean;
  };

  const { overlay, center, zoom } = computeOverlay(result);

  // satellite map for the layout overlay
  let mapDataUri: string | undefined;
  const key = process.env.GOOGLE_MAPS_API_KEY;
  if (key) {
    try {
      const res = await fetch(`https://maps.googleapis.com/maps/api/staticmap?center=${center.lat},${center.lng}&zoom=${zoom}&size=${W}x${H}&scale=2&maptype=satellite&key=${key}`);
      if (res.ok) mapDataUri = await toDataUri(Buffer.from(await res.arrayBuffer()), "image/png");
    } catch { /* map optional */ }
  }

  const images: PdfImages = {
    mapDataUri,
    renderDataUri: hasRender ? await toDataUri(await readBinary(`proposals/${id}-photos/render.jpg`), "image/jpeg") : undefined,
    photoDataUri: (photoCount ?? 0) > 0 ? await toDataUri(await readBinary(`proposals/${id}-photos/0.jpg`), "image/jpeg") : undefined,
  };

  const pdf = await renderProposalPdf({ result, narrative, images, overlay, createdAt });
  return { pdf, result };
}

/** GET ?id=xxx[&download=1] — stream the PDF (for a download button). */
export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get("id");
  if (!id || !/^[\w-]+$/.test(id)) return NextResponse.json({ error: "bad id" }, { status: 400 });
  const out = await buildPdf(id);
  if (!out) return NextResponse.json({ error: "not found" }, { status: 404 });
  return new NextResponse(new Uint8Array(out.pdf), {
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `inline; filename="solvio-proposal-${id}.pdf"`,
    },
  });
}

/** POST { id } — generate the PDF and file it in the user's Google Drive. */
export async function POST(req: NextRequest) {
  const { id } = (await req.json()) as { id?: string };
  if (!id || !/^[\w-]+$/.test(id)) return NextResponse.json({ error: "bad id" }, { status: 400 });

  const webhook = process.env.GOOGLE_DRIVE_WEBHOOK_URL;
  if (!webhook) return NextResponse.json({ archived: false, reason: "Google Drive not connected" });

  const out = await buildPdf(id);
  if (!out) return NextResponse.json({ error: "not found" }, { status: 404 });

  const addr = out.result.site.address.replace(/[^\w\s-]/g, "").trim().slice(0, 60) || "proposal";
  const filename = `Solvio Proposal — ${addr} — ${id}.pdf`;
  try {
    const res = await fetch(webhook, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        secret: process.env.GOOGLE_DRIVE_SECRET ?? "",
        filename,
        description: `${out.result.site.address} — generated by Solvio`,
        pdfBase64: out.pdf.toString("base64"),
      }),
    });
    const data = await res.json();
    if (!res.ok || data.error) return NextResponse.json({ archived: false, reason: data.error ?? `webhook HTTP ${res.status}` });
    return NextResponse.json({ archived: true, driveUrl: data.url });
  } catch (e) {
    return NextResponse.json({ archived: false, reason: String(e) });
  }
}
